# Generated by Django 5.2 on 2025-04-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_exercise_workout_workoutexercises_workout_exercises_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
    ]
