# Generated by Django 5.2 on 2025-04-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_workout_is_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
    ]
