# Generated by Django 5.2 on 2025-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_is_custom_workout_is_template_workout_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
    ]
