# Generated by Django 5.2 on 2025-05-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_workout_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_own_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='reps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
