# Generated by Django 5.2 on 2025-05-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_exercise_is_own_weight_alter_exerciseset_reps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseset',
            old_name='set_number',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='workoutexercises',
            name='sets',
        ),
        migrations.AddField(
            model_name='workoutexercises',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='workouts', through='tracker.WorkoutExercises', through_fields=('workout', 'exercise'), to='tracker.exercise'),
        ),
    ]
